# Generated by Django 2.1.2 on 2020-08-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200804_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='privacy_level',
        ),
    ]
