# Generated by Django 2.1.7 on 2021-01-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitors_gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=256)),
                ('competitors_category', models.CharField(choices=[('Mini', 'mini'), ('Junior', 'junior'), ('Cade', 'cade'), ('Senior', 'senior')], max_length=256)),
                ('competitors_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tournament_date', models.DateField(blank=True, null=True)),
                ('tournament_location', models.CharField(blank=True, max_length=256, null=True)),
                ('tournament_enrolment_close_date', models.DateTimeField()),
                ('tournament_competition_start_date', models.DateField()),
                ('tournament_competition_close_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_competitions', to='tournament.Tournament'),
        ),
    ]
