# Generated by Django 2.1.7 on 2021-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competitors_years',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
