version: '3'

services:
  martial_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_mart:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mart_user
      - POSTGRES_PASSWORD=mart_password
      - POSTGRES_DB=mart_db
  martial:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8150"]
    depends_on:
      - martial_db
    volumes:
      - .:/app/mart
    ports:
      - "8150:8150"
    stdin_open: true
    tty: true

volumes:
  node-modules:
  postgres_mart: