# Generated by Django 2.2.6 on 2020-12-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('alg', 'Algeria'), ('lib', 'Libya'), ('mar', 'Maroc'), ('tun', 'Tunisia')], max_length=200)),
                ('coach_name', models.CharField(max_length=200)),
                ('assistant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(max_length=200)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('wtf_gal', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('ml', 'Male'), ('fm', 'Female')], max_length=200)),
                ('date_of_birth', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
