# Generated by Django 2.1.7 on 2021-02-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='competition',
        ),
    ]
