# Generated by Django 2.1.2 on 2021-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('team', '0002_auto_20210114_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='competition',
        ),
        migrations.AddField(
            model_name='competitor',
            name='competition',
            field=models.ManyToManyField(to='tournament.Competition'),
        ),
    ]
