# Generated by Django 2.1.7 on 2021-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_competitor_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='weight',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
