# Generated by Django 2.1.2 on 2021-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='competition',
            field=models.ManyToManyField(blank=True, to='tournament.Competition'),
        ),
    ]
