# Generated by Django 2.1.7 on 2021-01-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='assistant_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
    ]
