# Generated by Django 2.1.7 on 2021-01-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('team', '0007_auto_20210127_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Competition')),
                ('competitors', models.ManyToManyField(related_name='participations', to='team.Competitor')),
            ],
        ),
    ]
