# Generated by Django 2.1.7 on 2021-01-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='competitors',
        ),
        migrations.AddField(
            model_name='competitor',
            name='participation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team.Participation'),
            preserve_default=False,
        ),
    ]
