# Generated by Django 2.1.7 on 2021-01-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20210127_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='participation',
        ),
        migrations.AddField(
            model_name='participation',
            name='competitors',
            field=models.ManyToManyField(related_name='participations', to='team.Competitor'),
        ),
        migrations.AddField(
            model_name='participation',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
            preserve_default=False,
        ),
    ]
